"""empty message

Revision ID: 069bc2165356
Revises: 697c78da78ae
Create Date: 2020-01-30 00:47:48.951049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069bc2165356'
down_revision = '697c78da78ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('email', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'email')
    # ### end Alembic commands ###
