"""empty message

Revision ID: 263441eee04b
Revises: 94402527f7d4
Create Date: 2020-01-29 23:34:58.200399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263441eee04b'
down_revision = '94402527f7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('uid', sa.Integer(), nullable=False, autoincrement=True))
    op.drop_column('User', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_column('User', 'uid')
    # ### end Alembic commands ###
