"""empty message

Revision ID: 0886d8058fb8
Revises: 
Create Date: 2020-01-30 17:12:24.424135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0886d8058fb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('userid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=80), nullable=False),
    sa.Column('lastName', sa.String(length=80), nullable=False),
    sa.Column('childFirstName', sa.String(length=80), nullable=False),
    sa.Column('childLastName', sa.String(length=80), nullable=False),
    sa.Column('userRole', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userid')
    )
    op.create_table('entry',
    sa.Column('entryid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_behavior', sa.String(length=255), nullable=False),
    sa.Column('home_school_goal', sa.String(length=255), nullable=False),
    sa.Column('action_plan_one', sa.String(length=255), nullable=False),
    sa.Column('action_plan_two', sa.String(length=255), nullable=True),
    sa.Column('action_plan_three', sa.String(length=255), nullable=True),
    sa.Column('action_plan_four', sa.String(length=255), nullable=True),
    sa.Column('action_plan_five', sa.String(length=255), nullable=True),
    sa.Column('action_plan_one_rating', sa.Integer(), nullable=False),
    sa.Column('action_plan_two_rating', sa.Integer(), nullable=True),
    sa.Column('action_plan_three_rating', sa.Integer(), nullable=True),
    sa.Column('action_plan_four_rating', sa.Integer(), nullable=True),
    sa.Column('action_plan_five_rating', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.userid'], ),
    sa.PrimaryKeyConstraint('entryid'),
    sa.UniqueConstraint('entryid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    op.drop_table('User')
    # ### end Alembic commands ###
