"""empty message

Revision ID: 30552bea2be7
Revises: 890f4e443442
Create Date: 2020-03-03 05:04:31.110509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30552bea2be7'
down_revision = '890f4e443442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ActionPlan', ['actionPlanId'])
    op.create_unique_constraint(None, 'Entry', ['entryid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Entry', type_='unique')
    op.drop_constraint(None, 'ActionPlan', type_='unique')
    # ### end Alembic commands ###
