"""empty message

Revision ID: 32e2eabaec16
Revises: 263441eee04b
Create Date: 2020-01-29 23:42:03.695897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e2eabaec16'
down_revision = '263441eee04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('childFirstName', sa.String(length=80), nullable=False))
    op.add_column('User', sa.Column('childLastName', sa.String(length=80), nullable=False))
    op.add_column('User', sa.Column('firstName', sa.String(length=80), nullable=False))
    op.add_column('User', sa.Column('lastName', sa.String(length=80), nullable=False))
    op.add_column('User', sa.Column('userRole', sa.String(length=80), nullable=False))
    op.alter_column('User', 'password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint('User_username_key', 'User', type_='unique')
    op.create_unique_constraint(None, 'User', ['firstName'])
    op.drop_column('User', 'usertype')
    op.drop_column('User', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('usertype', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'User', type_='unique')
    op.create_unique_constraint('User_username_key', 'User', ['username'])
    op.alter_column('User', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('User', 'userRole')
    op.drop_column('User', 'lastName')
    op.drop_column('User', 'firstName')
    op.drop_column('User', 'childLastName')
    op.drop_column('User', 'childFirstName')
    # ### end Alembic commands ###
