"""empty message

Revision ID: 491f513b885e
Revises: 32e2eabaec16
Create Date: 2020-01-30 00:17:33.919773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491f513b885e'
down_revision = '32e2eabaec16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('User_firstName_key', 'User', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('User_firstName_key', 'User', ['firstName'])
    # ### end Alembic commands ###
