"""empty message

Revision ID: 719b1f6dec59
Revises: 
Create Date: 2020-07-24 12:31:54.838560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719b1f6dec59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('userRole', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=1023), nullable=False),
    sa.Column('targetBehavior', sa.String(length=1023), nullable=False),
    sa.Column('homeSchoolGoal', sa.String(length=1023), nullable=False),
    sa.Column('email', sa.String(length=1023), nullable=False),
    sa.Column('phoneNumber', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ActionPlan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=True),
    sa.Column('stepName', sa.String(length=1023), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=True),
    sa.Column('actionPlanOne', sa.String(length=1023), nullable=False),
    sa.Column('actionPlanTwo', sa.String(length=1023), nullable=True),
    sa.Column('actionPlanThree', sa.String(length=1023), nullable=True),
    sa.Column('actionPlanFour', sa.String(length=1023), nullable=True),
    sa.Column('actionPlanFive', sa.String(length=1023), nullable=True),
    sa.Column('targetBehavior', sa.String(length=1023), nullable=False),
    sa.Column('homeSchoolGoal', sa.String(length=1023), nullable=False),
    sa.Column('goalRating', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('signature', sa.String(length=50000), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Entry')
    op.drop_table('ActionPlan')
    op.drop_table('User')
    # ### end Alembic commands ###
