"""empty message

Revision ID: 768cebb27857
Revises: 2ece0b0eb9e2
Create Date: 2020-03-25 02:21:13.678293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768cebb27857'
down_revision = '2ece0b0eb9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ActionPlan', ['id'])
    op.add_column('Entry', sa.Column('homeSchoolGoal', sa.String(length=255), nullable=False))
    op.add_column('Entry', sa.Column('targetBehavior', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'Entry', ['id'])
    op.add_column('User', sa.Column('homeSchoolGoal', sa.String(length=255), nullable=False))
    op.add_column('User', sa.Column('targetBehavior', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'User', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('User', 'targetBehavior')
    op.drop_column('User', 'homeSchoolGoal')
    op.drop_constraint(None, 'Entry', type_='unique')
    op.drop_column('Entry', 'targetBehavior')
    op.drop_column('Entry', 'homeSchoolGoal')
    op.drop_constraint(None, 'ActionPlan', type_='unique')
    # ### end Alembic commands ###
