"""empty message

Revision ID: 7e4099450bc3
Revises: bb15e44a3d77
Create Date: 2020-02-29 14:44:30.360202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4099450bc3'
down_revision = 'bb15e44a3d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('homeSchoolGoal', sa.String(length=255), nullable=False))
    op.add_column('User', sa.Column('idNum', sa.Integer(), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('targetBehavior', sa.String(length=255), nullable=False))
    op.drop_constraint('User_email_key', 'User', type_='unique')
    op.drop_constraint('User_userid_key', 'User', type_='unique')
    op.create_unique_constraint(None, 'User', ['idNum'])
    op.drop_column('User', 'childFirstName')
    op.drop_column('User', 'userid')
    op.drop_column('User', 'lastName')
    op.drop_column('User', 'email')
    op.drop_column('User', 'childLastName')
    op.drop_column('User', 'firstName')
    op.create_foreign_key(None, 'entry', 'User', ['user_id'], ['idNum'])
    op.drop_column('entry', 'home_school_goal')
    op.drop_column('entry', 'target_behavior')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('target_behavior', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('entry', sa.Column('home_school_goal', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.create_foreign_key('entry_user_id_fkey', 'entry', 'User', ['user_id'], ['userid'])
    op.add_column('User', sa.Column('firstName', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('childLastName', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('lastName', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('userid', sa.INTEGER(), server_default=sa.text('nextval(\'"User_userid_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.add_column('User', sa.Column('childFirstName', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'User', type_='unique')
    op.create_unique_constraint('User_userid_key', 'User', ['userid'])
    op.create_unique_constraint('User_email_key', 'User', ['email'])
    op.drop_column('User', 'targetBehavior')
    op.drop_column('User', 'idNum')
    op.drop_column('User', 'homeSchoolGoal')
    # ### end Alembic commands ###
