"""empty message

Revision ID: 9f3e283187a3
Revises: 0886d8058fb8
Create Date: 2020-01-30 17:14:16.482445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3e283187a3'
down_revision = '0886d8058fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'User', ['userid'])
    op.create_unique_constraint(None, 'entry', ['entryid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    # ### end Alembic commands ###
