"""empty message

Revision ID: b823ee201761
Revises: 7e4099450bc3
Create Date: 2020-03-01 15:17:31.118681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b823ee201761'
down_revision = '7e4099450bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('email', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'email')
    # ### end Alembic commands ###
