"""empty message

Revision ID: bb15e44a3d77
Revises: 9f3e283187a3
Create Date: 2020-01-30 22:16:05.248253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb15e44a3d77'
down_revision = '9f3e283187a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('goal_rating', sa.Integer(), nullable=False))
    op.drop_column('entry', 'action_plan_four_rating')
    op.drop_column('entry', 'action_plan_one_rating')
    op.drop_column('entry', 'action_plan_three_rating')
    op.drop_column('entry', 'action_plan_five_rating')
    op.drop_column('entry', 'action_plan_two_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('action_plan_two_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('action_plan_five_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('action_plan_three_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('action_plan_one_rating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('entry', sa.Column('action_plan_four_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('entry', 'goal_rating')
    # ### end Alembic commands ###
